"""create_hicounter

Revision ID: 0000
Revises: 
Create Date: 2023-07-13 11:40:56.495818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0000"
down_revision = None
branch_labels = None
depends_on = None
add_models: dict[str, str] = {"hicounter": "basic_hicounters"}
remove_models: dict[str, str] = {}
rename_models: dict[str, str] = {}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "basic_hicounters",
        sa.Column("user", sa.BigInteger(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("user"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("basic_hicounters")
    # ### end Alembic commands ###
