on:
  push:
    branches:
      - release
jobs:
  release_version:
    name: "Release New Version"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Get release version
        id: version
        run: |
          echo "RELEASE_VER=$(python -c \"from docs.conf import release; print(release, end='')\") >> "$GITHUB_OUTPUT"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.RELEASE_VER }}


      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.RELEASE_VER }}
          name: Release ${{ steps.version.outputs.RELEASE_VER }}
          body: ${{ steps.tag_version.outputs.changelog }}


